mybatis-plus:
  #POJO??????
  #mapper.xml?????
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: host.luke.musicweb.pojo
server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://81.68.212.127:3306/Music
    username: root
    password: onelastkiss
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1


